# Numpy
create an array

In [1]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr=np.array([1,2,3])

In [4]:
arr

array([1, 2, 3])

In [5]:
list_of_lists=([1,2,3],[4,5,6],[7,8,9])
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(5,28)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [8]:
np.arange(5,35,6)

array([ 5, 11, 17, 23, 29])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [16]:
np.ones((2,5,3),dtype=int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [17]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [24]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [25]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [27]:
np.random.rand(2,4,2)

array([[[0.31032021, 0.86271183],
        [0.40638761, 0.77523897],
        [0.58990196, 0.91723054],
        [0.60576578, 0.44065159]],

       [[0.35685189, 0.33097691],
        [0.02348402, 0.93298165],
        [0.85566333, 0.13812369],
        [0.49321452, 0.39402189]]])

In [30]:
np.random.randn(2,4)

array([[-0.6979197 ,  1.99916793,  0.90846378, -0.94550248],
       [-0.71294241, -0.55300495,  0.45753114, -0.64400201]])

In [31]:
np.random.rand(2,5)

array([[0.25371592, 0.80680196, 0.5830524 , 0.81062646, 0.9935703 ],
       [0.16723385, 0.14779004, 0.91988844, 0.61389218, 0.10836914]])

In [32]:
np.random.randint(0,10,15)

array([7, 5, 3, 3, 5, 6, 0, 5, 4, 7, 0, 8, 2, 2, 4])

In [33]:
np.random.randint(10,100,15)

array([43, 60, 65, 62, 99, 12, 92, 19, 98, 99, 10, 55, 34, 68, 22])

In [35]:
np.random.randint(20,56,100)

array([26, 37, 52, 52, 24, 34, 28, 35, 34, 24, 38, 22, 32, 22, 36, 29, 23,
       42, 28, 42, 25, 24, 44, 35, 54, 50, 21, 20, 55, 41, 42, 25, 37, 27,
       51, 43, 31, 31, 53, 31, 25, 45, 53, 43, 25, 47, 45, 31, 27, 47, 21,
       20, 40, 50, 44, 30, 30, 21, 42, 37, 25, 49, 27, 25, 32, 31, 23, 52,
       50, 46, 47, 43, 48, 25, 55, 21, 27, 43, 55, 31, 41, 31, 46, 30, 52,
       41, 43, 32, 21, 49, 55, 20, 36, 46, 27, 40, 38, 46, 43, 48])

In [36]:
sample_array=np.arange(2,200)
sample_array

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
       158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
       171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 18

In [38]:
rand_array=np.random.randint(0,10,5)
rand_array

array([5, 6, 5, 6, 7])

In [39]:
sample_array.min()

2

In [40]:
sample_array.argmin()

0

In [41]:
rand_array.argmin()

0